FROM python:3.9-slim

WORKDIR /app

COPY 7_napovedni_model_kot_spletna_storitev/requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY 7_napovedni_model_kot_spletna_storitev/ .

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]